version: '3.9'

networks:
  pronto:
    name: pronto

services:
  api-server:
    container_name: api-server
    build: 
      context: srv
      dockerfile: Dockerfile
    ports:
      - "7164:8080"
    networks:
      - pronto
    entrypoint: ["sleep", "infinity"]

  srv-0:
    container_name: srv-0
    build: 
        context: client
        dockerfile: Dockerfile
    entrypoint: ["./pronto-client"]
    networks:
      - pronto
  srv-1:
    container_name: srv-1
    build: 
        context: client
        dockerfile: Dockerfile
    networks:
      - pronto
    entrypoint: ["./pronto-client"]
